mmcxii/manhattan-project

- interfaces/IProduct.ts
- interfaces/IUser.ts
- models/Product.ts
- models/User.ts
- models/index.ts
- models/placeholder.txt
Initial implementations for User and Product models. Also included DB connection in models/index.ts for now.
> Mongoose models

- db.ts
- routes/api/placeholder.txt
- routes/index.ts
- routes/userRoutes.ts
- server.ts
- Refactored db connection to use connect() rather than createConnection(). Expose single "connect" method from db.ts, which is called in server.ts.
- Created index.ts in /routes for configuring express Router. Router object configured by separate route types (e.g. User, Product, etc) before being attached to express app.
- Begin implementing User routes
- Use parent Router for api routes, with nested routers for each api resource.
> Db connection refactor + initial user routes

- client/public/index.html
- routes/htmlRoutes.ts
- routes/index.ts
- server.ts
- Set Express static path to client/public
- Add express.json() middleware
- Create root html route to serve index.html
> use static path and add root html route

- client/src/Pages/User/User.tsx
- client/src/Store.tsx
- package-lock.json
Basic fields for testing data population on /user page
> User page *Don't Delete*

- interfaces/IComment.ts
- interfaces/IUpdateContext.ts
- interfaces/IUser.ts
- models/Comment.ts
- models/User.ts
- routes/userRoutes.ts
- util/UserUtilities.ts
- More model work. 👍 
- Created Comment Schema/Model. 👍 
- Use Interfaces for mongoose documents **AND** models. 👍 
- For future schema and document methods.  💯
- Still more work to do. Sorry :(  👎
> Models - *KEEP OPEN*

- client/src/App.tsx
- client/src/Elements/Layout/Footer/Footer.tsx
- client/src/Elements/Layout/Footer/ProjectInfo/InfoItem.tsx
- client/src/Elements/Layout/Footer/ProjectInfo/ProjectInfo.tsx
- client/src/Elements/Layout/Footer/ProjectInfo/index.ts
- client/src/Elements/Layout/Footer/TeamMembers/TeamMember.tsx
- client/src/Elements/Layout/Footer/TeamMembers/TeamMembers.tsx
- client/src/Elements/Layout/Footer/TeamMembers/index.ts
- client/src/Elements/Layout/Header/Nav/Nav.tsx
- client/src/Elements/Layout/Header/Nav/NavItem.tsx
- client/src/Pages/Router.tsx
- client/src/Store.tsx
Footer and nav are styled up, if you have feedback re: styles for anything, want something changed, have a better idea, etc lemme know.
> Design system

- .gitignore
- package.json
- server.ts
- mongoose is already set up to use connection string set in env var "MONGODB_URI"
> add dotenv package

- models/User.ts
- routes/userRoutes.ts
Created a DTO class for User: UserData. This class defines the shape of our User objects we want to return (or optinally consume) from callers.
> create User DTO class

- client/package.json
- client/src/Elements/Components/Form/Input.tsx
- client/src/Elements/Layout/Header/Nav/Nav.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/Login/index.ts
- client/src/Pages/Router.tsx
- client/src/Pages/User/User.tsx
- client/src/Store/UserContext.tsx
- interfaces/IUser.ts
- models/User.ts
> Login Page *Don't Delete Branch*

- client/src/App.tsx
- client/src/Hooks/index.ts
- client/src/Hooks/useLSUserInfo.ts
- client/src/Pages/Login/Login.tsx
User data is stored in LS when they log in, this is read from LS when the app mounts and saved in UserContext. Functionality abstracted to custom hook for cleanliness in App.tsx as well as possible reuse if needed elsewhere.
> User Info stored and read from LS *Don't Delete*

- client/package-lock.json
- client/package.json
- client/src/Pages/SearchForm/SearchForm.tsx
- interfaces/index.ts
- models/Product.ts
- routes/productRoutes.ts
This change modifies the api search to use query string parameters. Hits the product route, which will need to be updated to parse query string and filter accordingly.
> use query string for product search

- util/Seed.js
Changed product 'type' from string to number, since they are represented as an Enum in main typescript files
> update seed schema 'type' type

- models/Product.ts
- models/index.ts
- routes/productRoutes.ts
- util/Seed.js
FYI - Product text index has already been applied in Atlas DB.
> Product search

- routes/Errors.ts
- routes/Status.ts
- routes/index.ts
- routes/searchRoutes.ts
- routes/userRoutes.ts
- Added status functions the set a Response status and message. Can be used to keep api returns consistent.
- Updated user routes to use status functions
- Branch can be killed. Will create others as needed for other router updates.
> Error handling

- client/src/Elements/Components/Avatar.tsx
- client/src/Elements/Components/AvatarUpdater.tsx
- client/src/Elements/Components/FileInput.tsx
- client/src/Elements/Components/Icon.tsx
- client/src/Elements/Components/index.ts
- client/src/Pages/EditUser/EditUser.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/User/UserInfo.tsx
- client/src/Store/UserContext.tsx
- client/src/Utilities/index.ts
- client/src/Utilities/transform.ts
- routes/fileRoutes.ts
- util/AWS.ts
Show avatar (user.imgUrl) on user and user edit page. Allow avatar updates by uploading image file. By no means a great solution, but it seems to work.
> Avatar edit

- models/User.ts
- routes/authRoutes.ts
- util/AWS.ts
- add document id to UserData
- Prettier formatting changes
> add id to UserData

- interfaces/IProduct.ts
- models/Product.ts
- routes/productRoutes.ts
✅  Added voting endpoints in product routes
ℹ️  GET, PUT /api/products/:id/upvotes
ℹ️  GET, PUT /api/products/:id/downvotes
> Product routes

- client/src/Pages/SearchForm/ResultsItem/BeerDetails.tsx
- client/src/Pages/SearchForm/ResultsItem/MixedDetails.tsx
- client/src/Pages/SearchForm/ResultsItem/ResultsItem.tsx
- client/src/Pages/SearchForm/SearchForm.tsx
some stylized changes to results / mixed / beer . need to fix overflow text and margins --> switch to grid
> Mixedresults

- client/src/Pages/SearchForm/ResultsItem/ResultsItem.tsx
Side scrolling bug should now be fixed.
> responsive layout for results items

- client/src/Elements/Components/Rating/Rating.tsx
- client/src/Elements/Components/Rating/UpvoteDownvote.tsx
- client/src/Elements/Components/UserIcon.tsx
- client/src/Elements/Components/index.ts
- client/src/Elements/Layout/Container.tsx
- client/src/Hooks/index.ts
- client/src/Hooks/useDocumentTitle.ts
- client/src/Hooks/useTitle.ts
- client/src/Pages/CreateUser/CreateUser.tsx
- client/src/Pages/EditUser/EditUser.tsx
- client/src/Pages/ErrorPage/ErrorPage.tsx
- client/src/Pages/Home/Home.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/Logout/Logout.tsx
- client/src/Pages/ProductDetail/CommentsSection/CommentsList/Comment.tsx
- client/src/Pages/ProductDetail/ProductDetail.tsx
- client/src/Pages/SearchForm/SearchForm.tsx
- client/src/Pages/User/FollowsAndFollowers/List/User.tsx
- client/src/Pages/User/User.tsx
Comment redesign and a new hook used for setting the title
> Comment redesign

- interfaces/IProduct.ts
- interfaces/index.ts
- models/Comment.ts
- models/Product.ts
- routes/productRoutes.ts
Created a new ProductData DTO class. Includes product rating. Also updated routes to use ProductData and CommentData.
> Product & Comment data changes

- client/package-lock.json
- client/package.json
- client/src/Elements/Components/Card.tsx
- client/src/Elements/Components/Rating/Rating.tsx
- client/src/Elements/Components/Rating/UpvoteDownvote.tsx
- client/src/Elements/Layout/Header/Logo.tsx
- client/src/Pages/ProductDetail/CocktailIngredients.tsx
- client/src/Pages/ProductDetail/CommentsSection/CommentsList/Comment.tsx
- client/src/Pages/ProductDetail/ProductDetail.tsx
- client/src/Pages/ProductDetail/ProductIngredients.tsx
- client/src/Pages/SearchForm/ResultsItem/ResultsItem.tsx
- client/src/Pages/SearchForm/SearchForm.tsx
- client/src/Store/IComment.tsx
- client/src/Store/IProduct.tsx
- interfaces/IComment.ts
- models/Comment.ts
- routes/commentRoutes.ts
- routes/productRoutes.ts
- Overall product details formatting. Added margin to space out details a bit.
- Added beer type and description to product details
- Utilize 'rating' in comment and product data to update respective rating values
- Restyle UpvoteDownvote component to remove outline, use larger icons, and place rating value centered between arrows.
- Display search result count
- Clear old search results after search type switch
- Extract reusable product search function in SearchForm
- Animate site title on load: shift and fade
- Apply fade animation to cards and comments
- Use table to display cocktail ingredients (for alignment)
- Add dateCreated to Comment model
- Add moment npm pkg to client deps; include formatted date string in comment cards
> UI/UX Polish - Keep Open

- client/src/Elements/Components/AvatarUpdater.tsx
- models/Comment.ts
- clear avatar cache after update
- set comment create date
> Fixes - Keep Open

- client/src/Elements/Components/Card.tsx
- client/src/Elements/Components/FollowButton.tsx
- client/src/Elements/Layout/Footer/TeamMembers/TeamMembers.tsx
- client/src/Pages/EditUser/EditUser.tsx
> Final changes
